import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { ThemeToggle } from "@/components/ThemeToggle";
import { BookOpen, Brain, Calendar, TrendingUp } from "lucide-react";

export default function Home() {
  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <span className="text-2xl">🧠</span>
            <span className="text-xl font-semibold">MindFlow</span>
          </div>
          <div className="flex items-center gap-3">
            <ThemeToggle />
            <Link href="/login">
              <Button variant="ghost" data-testid="button-login">
                Login
              </Button>
            </Link>
            <Link href="/signup">
              <Button data-testid="button-signup">
                Get Started
              </Button>
            </Link>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="container mx-auto px-4 py-16 md:py-24">
        <div className="text-center max-w-3xl mx-auto">
          <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold mb-6 leading-tight">
            Transform Your Study Sessions with AI 📝
          </h1>
          <p className="text-lg md:text-xl text-muted-foreground mb-8 leading-relaxed">
            MindFlow combines artificial intelligence with mental wellness to create personalized study plans that adapt to your emotional state and learning style.
          </p>
          <Link href="/signup">
            <Button size="lg" className="text-base px-8" data-testid="button-hero-cta">
              Start Your Journey ⚡
            </Button>
          </Link>
        </div>
      </section>

      {/* Features Grid */}
      <section className="container mx-auto px-4 py-12 md:py-16">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          <Card className="p-6 hover-elevate transition-shadow">
            <div className="text-4xl mb-4">🤖</div>
            <h3 className="text-lg font-semibold mb-2">AI-Powered Plans</h3>
            <p className="text-sm text-muted-foreground">
              Get personalized study schedules generated by advanced AI that understands your needs.
            </p>
          </Card>

          <Card className="p-6 hover-elevate transition-shadow">
            <div className="text-4xl mb-4">😊</div>
            <h3 className="text-lg font-semibold mb-2">Emotion Tracking</h3>
            <p className="text-sm text-muted-foreground">
              Monitor your mental wellness and adapt your study approach based on how you feel.
            </p>
          </Card>

          <Card className="p-6 hover-elevate transition-shadow">
            <div className="text-4xl mb-4">📊</div>
            <h3 className="text-lg font-semibold mb-2">Progress Analytics</h3>
            <p className="text-sm text-muted-foreground">
              Track your study sessions, completion rates, and productivity trends over time.
            </p>
          </Card>

          <Card className="p-6 hover-elevate transition-shadow">
            <div className="text-4xl mb-4">🎯</div>
            <h3 className="text-lg font-semibold mb-2">Smart Task Management</h3>
            <p className="text-sm text-muted-foreground">
              Organize your workload with priority-based task lists that keep you focused.
            </p>
          </Card>
        </div>
      </section>

      {/* How It Works */}
      <section className="container mx-auto px-4 py-12 md:py-16">
        <h2 className="text-3xl font-bold text-center mb-12">How MindFlow Works</h2>
        <div className="max-w-4xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-8">
          <div className="text-center">
            <div className="w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center mx-auto mb-4">
              <Brain className="w-8 h-8 text-primary" />
            </div>
            <h3 className="font-semibold mb-2">1. Brain Dump</h3>
            <p className="text-sm text-muted-foreground">
              Share your tasks, available time, and current challenges
            </p>
          </div>

          <div className="text-center">
            <div className="w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center mx-auto mb-4">
              <Calendar className="w-8 h-8 text-primary" />
            </div>
            <h3 className="font-semibold mb-2">2. AI Planning</h3>
            <p className="text-sm text-muted-foreground">
              Get a customized study schedule tailored to you
            </p>
          </div>

          <div className="text-center">
            <div className="w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center mx-auto mb-4">
              <TrendingUp className="w-8 h-8 text-primary" />
            </div>
            <h3 className="font-semibold mb-2">3. Track & Adapt</h3>
            <p className="text-sm text-muted-foreground">
              Monitor progress and adjust plans based on your emotions
            </p>
          </div>
        </div>
      </section>

      {/* About Section */}
      <section className="container mx-auto px-4 py-12 md:py-16 bg-card/50 rounded-lg my-12">
        <div className="max-w-3xl mx-auto text-center">
          <h2 className="text-3xl font-bold mb-6">Mental Wellness Meets Productivity</h2>
          <p className="text-muted-foreground mb-4 leading-relaxed">
            MindFlow was built on the belief that effective studying isn't just about time management—it's about understanding your mental state and working with it, not against it.
          </p>
          <p className="text-muted-foreground leading-relaxed">
            Our AI doesn't just schedule tasks; it creates plans that account for your stress levels, motivation, and learning preferences, helping you study smarter and feel better.
          </p>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t mt-16">
        <div className="container mx-auto px-4 py-8 text-center text-sm text-muted-foreground">
          <p>&copy; 2024 MindFlow. Your mental wellness study companion.</p>
        </div>
      </footer>
    </div>
  );
}
